#指定基底文件為jupyter/base-notebook
FROM jupyter/base-notebook

#更新
RUN apt-get update
RUN apt-get upgrade

#安裝git
RUN apt-get -y install git-all 

#安裝pyenv
RUN git clone https://github.com/yyuu/pyenv.git ~/.pyenv
RUN git clone https://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv

#更新
RUN apt-get update

#安裝一些東西
RUN apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm vim

#設定環境參數
RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
RUN echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
RUN echo 'eval "$(pyenv init -)"' >> ~/.bashrc

#環境參數更新
RUN source ~/.bashrc

#安裝gcc
RUN apt-get install gcc

#安裝python3.6.7
RUN apt-get install zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel xz xz-devel libffi-devel

RUN CFLAGS="-I$(brew --prefix openssl)/include" LDFLAGS="-L$(brew --prefix openssl)/lib" pyenv install -v 3.6.7

#切換成3.6.7版本
RUN pyenv global 3.6.7

#安裝flask 0.12, request, line-bot-sdk
RUN pip install --upgrade pip
RUN pip install flask requests line-bot-sdk

#安裝tensorflow
RUN pip install --ignore-installed --upgrade tensorflow
RUN pip install tensorflow-hub